# Generated by Django 2.2.4 on 2020-09-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20200913_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='Customer_name',
            new_name='customer_name',
        ),
    ]
